services:
  victor_prdh_recaptcha_bundle.recaptcha_type:
    class: VictorPrdh\RecaptchaBundle\Form\ReCaptchaType
    arguments:
      $parameterBag: "@parameter_bag"
    public: true
    autowire: true
    tags:
      - { name: form.type, alias: captcha }

  ReCaptcha\ReCaptcha:
        arguments:
            - '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
  