services:
  victor_prdh_recaptcha_bundle.response_subscriber:
    class: VictorPrdh\RecaptchaBundle\EventSubscriber\ResponseSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
    tags:
      - { name: kernel.event_subscriber }
  
  victor_prdh_recaptcha_bundle.recaptcha_type:
    class: VictorPrdh\RecaptchaBundle\Form\ReCaptchaType
    arguments:
      $parameterBag: "@parameter_bag"
    public: true
    autowire: true
    tags:
      - { name: form.type, alias: captcha }

  recaptcha.recaptcha:
    class: ReCaptcha\ReCaptcha
    arguments:
      $secret: '%recaptcha.secret%'
  